area_info:
  gdf_dir_path: asset/area_geojson
  area_info_sqlite_path: asset/area_code.sqlite

traffic_sign:
  color:
    red: '#B5273C'
    white: '#FFFFFF'
    yellow: '#FFCD00'
    black: '#000000'
    green: '#006E55'
  font_path:
    A: asset/font/SourceHanSansSC-Bold.otf
    B: asset/font/jtbz_B.ttf
    C: asset/font/jtbz_C.ttf
  way_num_pad:
    template_path: asset/template/way_num.svg
#    width: 400
#    height: 200
#    word:
#      x: 50
#      y: 50
#      width: 300
#      height: 100
#    color:
#      background:
#        national: red
#        province: yellow
#        other: white
#      stroke:
#        national: white
#        province: black
#        other: black
  expwy_code_sign:
#    color:
#      background:
#        banner:
#          national: red
#          province: yellow
#        main: green
#      stroke:
#        banner:
#          national: white
#          province: black
#        main: white
    without_name:
      num_1:
        template_path: asset/template/expwy_1.svg
#        code:
#          x: 150
#          y: 370
#          width: 700
#          height: 450
#        banner_text:
#          national:
#            x: 150
#            y: 80
#            width: 700
#            height: 100
#          province:
#            x: 250
#            y: 80
#            width: 500
#            height: 100
      num_2:
        template_path: asset/template/expwy_2.svg
#        code:
#          x: 90
#          y: 370
#          width: 1070
#          height: 450
#        banner_text:
#          national:
#            x: 275
#            y: 80
#            width: 700
#            height: 100
#          province:
#            x: 359.1
#            y: 80
#            width: 500
#            height: 100
      num_4:
        template_path: asset/template/expwy_4.svg
#        code:
#          big:
#            x: 90
#            y: 370
#            width: 1070
#            height: 450
#          small:
#            x: 1220
#            y: 520
#            width: 390
#            height: 300
#        banner_text:
#          national:
#            x: 355
#            y: 80
#            width: 990
#            height: 100
#          province:
#            x: 355
#            y: 80
#            width: 990
#            height: 100
    with_name:
      num_1:
        template_path: asset/template/expwy_1_name.svg
#        code:
#          x: 150
#          y: 340
#          width: 700
#          height: 450
#        name:
#          x: 100
#          y: 860
#          width: 800
#          height: 200
#        banner_text:
#          national:
#            x: 150
#            y: 110
#            width: 700
#            height: 100
#          province:
#            x: 250
#            y: 110
#            width: 500
#            height: 100
      num_2:
        template_path: asset/template/expwy_2_name.svg
#        code:
#          x: 90
#          y: 340
#          width: 1070
#          height: 450
#        name:
#          x: 150
#          y: 860
#          width: 950
#          height: 200
#        banner_text:
#          national:
#            x: 275
#            y: 110
#            width: 700
#            height: 100
#          province:
#            x: 359.1
#            y: 110
#            width: 500
#            height: 100
      num_4:
        template_path: asset/template/expwy_4_name.svg
#        code:
#          big:
#            x: 90
#            y: 340
#            width: 1070
#            height: 450
#          small:
#            x: 1220
#            y: 490
#            width: 390
#            height: 300
#        name:
#          x: 150
#          y: 860
#          width: 1400
#          height: 200
#        banner_text:
#          national:
#            x: 355
#            y: 110
#            width: 990
#            height: 100
#          province:
#            x: 355
#            y: 110
#            width: 990
#            height: 100

video_info_layer:
  font_path:
    chinese: asset/font/SourceHanSans_static_super_otc.ttc
    english: asset/font/SourceSans3-Regular.otf
  img_path:
    compass: asset/compass.svg
    route_time_sep: asset/route_time_sep.svg
  frame:
    width: 3840
    height: 2160
    dpi: 72
    min_space: 48
    area:
      chinese:
        x: 191.8085
        y: 1924
      english:
        x: 192
        y: 1997
    road:
      x: 1464
      middle_y: 1988
      sign:
        width: 126
        height: 128
        space: 24
        char_space: 48
      chinese_y: 1924
      english_y: 1997
    compass:
      x: 2432
      y: 1924
    route_time:
      used:
        route:
          right_x: 2978
          y: 1924
        time:
          right_x: 2978
          y: 1997
      sep:
        x: 3002
        y: 1924
      remain:
        route:
          x: 3117
          y: 1924
        time:
          x: 3117
          y: 1997
    altitude:
      num:
        right_x: 3483
        y: 1924
      unit:
        right_x: 3483
        y: 1997
    speed:
      num:
        right_x: 3649
        y: 1924
      unit:
        right_x: 3649
        y: 1997